FPPOPTS='$(DEFINE)GENIENX=36 $(DEFINE)GENIENY=36 $(DEFINE)GOLDSTEINNLONS=36 $(DEFINE)GOLDSTEINNLATS=36 $(DEFINE)GOLDSTEINNLEVS=16 $(DEFINE)GOLDSTEINNTRACS=14 $(DEFINE)SEDGEMNLONS=36 $(DEFINE)SEDGEMNLATS=36 $(DEFINE)SEDGEMNLONS=36 $(DEFINE)SEDGEMNLATS=36 $(DEFINE)ROKGEMNLONS=36 $(DEFINE)ROKGEMNLATS=36 '
MODULE_NAMES='embm goldstein goldsteinseaice biogem atchem '
FPPOPTS2='$(DEFINE)USE_embm $(DEFINE)USE_goldstein $(DEFINE)USE_goldsteinseaice $(DEFINE)USE_biogem $(DEFINE)USE_atchem '
